version: '3.9'

services:
  app:
    container_name: 'wordlejs_http'
    tty: true
    stdin_open: true
    image: 'php:7.2-apache'
    volumes:
      - '.:/var/www/html/'
    networks:
      - default
  resources:
    container_name: 'wordlejs_resources'
    tty: true
    stdin_open: true
    image: 'node:10-alpine'
    volumes:
      - './resources/:/var/www/resources/'
    networks:
      - default

networks:
  default: 
    name: 'wordlejs_network'
